/*
 * This file is generated by jOOQ.
*/
package de.vorb.sokrates.db.jooq;


import de.vorb.sokrates.db.jooq.tables.Page;
import de.vorb.sokrates.db.jooq.tables.PageTag;
import de.vorb.sokrates.db.jooq.tables.Tag;
import de.vorb.sokrates.db.jooq.tables.records.PageRecord;
import de.vorb.sokrates.db.jooq.tables.records.PageTagRecord;
import de.vorb.sokrates.db.jooq.tables.records.TagRecord;

import javax.annotation.Generated;

import org.jooq.ForeignKey;
import org.jooq.Identity;
import org.jooq.UniqueKey;
import org.jooq.impl.AbstractKeys;


/**
 * A class modelling foreign key relationships and constraints of tables of 
 * the <code>PUBLIC</code> schema.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.10.2"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Keys {

    // -------------------------------------------------------------------------
    // IDENTITY definitions
    // -------------------------------------------------------------------------

    public static final Identity<PageRecord, Long> IDENTITY_PAGE = Identities0.IDENTITY_PAGE;
    public static final Identity<TagRecord, Long> IDENTITY_TAG = Identities0.IDENTITY_TAG;

    // -------------------------------------------------------------------------
    // UNIQUE and PRIMARY KEY definitions
    // -------------------------------------------------------------------------

    public static final UniqueKey<PageRecord> CONSTRAINT_2 = UniqueKeys0.CONSTRAINT_2;
    public static final UniqueKey<PageRecord> CONSTRAINT_25 = UniqueKeys0.CONSTRAINT_25;
    public static final UniqueKey<PageRecord> CONSTRAINT_255 = UniqueKeys0.CONSTRAINT_255;
    public static final UniqueKey<PageTagRecord> CONSTRAINT_6 = UniqueKeys0.CONSTRAINT_6;
    public static final UniqueKey<TagRecord> CONSTRAINT_1 = UniqueKeys0.CONSTRAINT_1;
    public static final UniqueKey<TagRecord> CONSTRAINT_14 = UniqueKeys0.CONSTRAINT_14;

    // -------------------------------------------------------------------------
    // FOREIGN KEY definitions
    // -------------------------------------------------------------------------

    public static final ForeignKey<PageTagRecord, PageRecord> CONSTRAINT_61 = ForeignKeys0.CONSTRAINT_61;
    public static final ForeignKey<PageTagRecord, TagRecord> CONSTRAINT_61F = ForeignKeys0.CONSTRAINT_61F;

    // -------------------------------------------------------------------------
    // [#1459] distribute members to avoid static initialisers > 64kb
    // -------------------------------------------------------------------------

    private static class Identities0 extends AbstractKeys {
        public static Identity<PageRecord, Long> IDENTITY_PAGE = createIdentity(Page.PAGE, Page.PAGE.ID);
        public static Identity<TagRecord, Long> IDENTITY_TAG = createIdentity(Tag.TAG, Tag.TAG.ID);
    }

    private static class UniqueKeys0 extends AbstractKeys {
        public static final UniqueKey<PageRecord> CONSTRAINT_2 = createUniqueKey(Page.PAGE, "CONSTRAINT_2", Page.PAGE.ID);
        public static final UniqueKey<PageRecord> CONSTRAINT_25 = createUniqueKey(Page.PAGE, "CONSTRAINT_25", Page.PAGE.SOURCE_FILE_PATH);
        public static final UniqueKey<PageRecord> CONSTRAINT_255 = createUniqueKey(Page.PAGE, "CONSTRAINT_255", Page.PAGE.URL);
        public static final UniqueKey<PageTagRecord> CONSTRAINT_6 = createUniqueKey(PageTag.PAGE_TAG, "CONSTRAINT_6", PageTag.PAGE_TAG.TAG_ID, PageTag.PAGE_TAG.PAGE_ID);
        public static final UniqueKey<TagRecord> CONSTRAINT_1 = createUniqueKey(Tag.TAG, "CONSTRAINT_1", Tag.TAG.ID);
        public static final UniqueKey<TagRecord> CONSTRAINT_14 = createUniqueKey(Tag.TAG, "CONSTRAINT_14", Tag.TAG.NAME);
    }

    private static class ForeignKeys0 extends AbstractKeys {
        public static final ForeignKey<PageTagRecord, PageRecord> CONSTRAINT_61 = createForeignKey(de.vorb.sokrates.db.jooq.Keys.CONSTRAINT_2, PageTag.PAGE_TAG, "CONSTRAINT_61", PageTag.PAGE_TAG.PAGE_ID);
        public static final ForeignKey<PageTagRecord, TagRecord> CONSTRAINT_61F = createForeignKey(de.vorb.sokrates.db.jooq.Keys.CONSTRAINT_1, PageTag.PAGE_TAG, "CONSTRAINT_61F", PageTag.PAGE_TAG.TAG_ID);
    }
}
