/*
 * This file is generated by jOOQ.
*/
package de.vorb.sokrates.db.jooq.tables.pojos;


import java.io.Serializable;
import java.sql.Timestamp;

import javax.annotation.Generated;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.10.2"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Page implements Serializable {

    private static final long serialVersionUID = 844651528;

    private Long      id;
    private String    path;
    private String    title;
    private Timestamp createdAt;
    private Timestamp lastModifiedAt;
    private byte[]    checksum;

    public Page() {}

    public Page(Page value) {
        this.id = value.id;
        this.path = value.path;
        this.title = value.title;
        this.createdAt = value.createdAt;
        this.lastModifiedAt = value.lastModifiedAt;
        this.checksum = value.checksum;
    }

    public Page(
        Long      id,
        String    path,
        String    title,
        Timestamp createdAt,
        Timestamp lastModifiedAt,
        byte[]    checksum
    ) {
        this.id = id;
        this.path = path;
        this.title = title;
        this.createdAt = createdAt;
        this.lastModifiedAt = lastModifiedAt;
        this.checksum = checksum;
    }

    public Long getId() {
        return this.id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public String getPath() {
        return this.path;
    }

    public void setPath(String path) {
        this.path = path;
    }

    public String getTitle() {
        return this.title;
    }

    public void setTitle(String title) {
        this.title = title;
    }

    public Timestamp getCreatedAt() {
        return this.createdAt;
    }

    public void setCreatedAt(Timestamp createdAt) {
        this.createdAt = createdAt;
    }

    public Timestamp getLastModifiedAt() {
        return this.lastModifiedAt;
    }

    public void setLastModifiedAt(Timestamp lastModifiedAt) {
        this.lastModifiedAt = lastModifiedAt;
    }

    public byte[] getChecksum() {
        return this.checksum;
    }

    public void setChecksum(byte... checksum) {
        this.checksum = checksum;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("Page (");

        sb.append(id);
        sb.append(", ").append(path);
        sb.append(", ").append(title);
        sb.append(", ").append(createdAt);
        sb.append(", ").append(lastModifiedAt);
        sb.append(", ").append("[binary...]");

        sb.append(")");
        return sb.toString();
    }
}
