/*
 * This file is generated by jOOQ.
*/
package de.vorb.sokrates.db.jooq.tables.pojos;


import java.io.Serializable;
import java.nio.file.Path;
import java.time.LocalDate;
import java.util.Locale;

import javax.annotation.Generated;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.10.2"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Page implements Serializable {

    private static final long serialVersionUID = -1380288766;

    private Long      id;
    private Path      sourceFilePath;
    private String    sourceFileFormat;
    private Path      outputFilePath;
    private String    title;
    private LocalDate createdAt;
    private LocalDate lastModifiedAt;
    private Locale    locale;
    private byte[]    checksum;

    public Page() {}

    public Page(Page value) {
        this.id = value.id;
        this.sourceFilePath = value.sourceFilePath;
        this.sourceFileFormat = value.sourceFileFormat;
        this.outputFilePath = value.outputFilePath;
        this.title = value.title;
        this.createdAt = value.createdAt;
        this.lastModifiedAt = value.lastModifiedAt;
        this.locale = value.locale;
        this.checksum = value.checksum;
    }

    public Page(
        Long      id,
        Path      sourceFilePath,
        String    sourceFileFormat,
        Path      outputFilePath,
        String    title,
        LocalDate createdAt,
        LocalDate lastModifiedAt,
        Locale    locale,
        byte[]    checksum
    ) {
        this.id = id;
        this.sourceFilePath = sourceFilePath;
        this.sourceFileFormat = sourceFileFormat;
        this.outputFilePath = outputFilePath;
        this.title = title;
        this.createdAt = createdAt;
        this.lastModifiedAt = lastModifiedAt;
        this.locale = locale;
        this.checksum = checksum;
    }

    public Long getId() {
        return this.id;
    }

    public Page setId(Long id) {
        this.id = id;
        return this;
    }

    public Path getSourceFilePath() {
        return this.sourceFilePath;
    }

    public Page setSourceFilePath(Path sourceFilePath) {
        this.sourceFilePath = sourceFilePath;
        return this;
    }

    public String getSourceFileFormat() {
        return this.sourceFileFormat;
    }

    public Page setSourceFileFormat(String sourceFileFormat) {
        this.sourceFileFormat = sourceFileFormat;
        return this;
    }

    public Path getOutputFilePath() {
        return this.outputFilePath;
    }

    public Page setOutputFilePath(Path outputFilePath) {
        this.outputFilePath = outputFilePath;
        return this;
    }

    public String getTitle() {
        return this.title;
    }

    public Page setTitle(String title) {
        this.title = title;
        return this;
    }

    public LocalDate getCreatedAt() {
        return this.createdAt;
    }

    public Page setCreatedAt(LocalDate createdAt) {
        this.createdAt = createdAt;
        return this;
    }

    public LocalDate getLastModifiedAt() {
        return this.lastModifiedAt;
    }

    public Page setLastModifiedAt(LocalDate lastModifiedAt) {
        this.lastModifiedAt = lastModifiedAt;
        return this;
    }

    public Locale getLocale() {
        return this.locale;
    }

    public Page setLocale(Locale locale) {
        this.locale = locale;
        return this;
    }

    public byte[] getChecksum() {
        return this.checksum;
    }

    public Page setChecksum(byte... checksum) {
        this.checksum = checksum;
        return this;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("Page (");

        sb.append(id);
        sb.append(", ").append(sourceFilePath);
        sb.append(", ").append(sourceFileFormat);
        sb.append(", ").append(outputFilePath);
        sb.append(", ").append(title);
        sb.append(", ").append(createdAt);
        sb.append(", ").append(lastModifiedAt);
        sb.append(", ").append(locale);
        sb.append(", ").append("[binary...]");

        sb.append(")");
        return sb.toString();
    }
}
