/*
 * This file is generated by jOOQ.
*/
package de.vorb.sokrates.db.jooq.tables.pojos;


import java.io.Serializable;

import javax.annotation.Generated;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.10.8"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class PageTag implements Serializable {

    private static final long serialVersionUID = 306209925;

    private Long pageId;
    private Long tagId;

    public PageTag() {}

    public PageTag(PageTag value) {
        this.pageId = value.pageId;
        this.tagId = value.tagId;
    }

    public PageTag(
        Long pageId,
        Long tagId
    ) {
        this.pageId = pageId;
        this.tagId = tagId;
    }

    public Long getPageId() {
        return this.pageId;
    }

    public PageTag setPageId(Long pageId) {
        this.pageId = pageId;
        return this;
    }

    public Long getTagId() {
        return this.tagId;
    }

    public PageTag setTagId(Long tagId) {
        this.tagId = tagId;
        return this;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("PageTag (");

        sb.append(pageId);
        sb.append(", ").append(tagId);

        sb.append(")");
        return sb.toString();
    }
}
