/*
 * This file is generated by jOOQ.
*/
package de.vorb.sokrates.db.jooq.tables.daos;


import de.vorb.sokrates.db.jooq.tables.PageTag;
import de.vorb.sokrates.db.jooq.tables.records.PageTagRecord;

import java.util.List;

import javax.annotation.Generated;

import org.jooq.Configuration;
import org.jooq.Record2;
import org.jooq.impl.DAOImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.10.2"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class PageTagDao extends DAOImpl<PageTagRecord, de.vorb.sokrates.db.jooq.tables.pojos.PageTag, Record2<Long, Long>> {

    /**
     * Create a new PageTagDao without any configuration
     */
    public PageTagDao() {
        super(PageTag.PAGE_TAG, de.vorb.sokrates.db.jooq.tables.pojos.PageTag.class);
    }

    /**
     * Create a new PageTagDao with an attached configuration
     */
    public PageTagDao(Configuration configuration) {
        super(PageTag.PAGE_TAG, de.vorb.sokrates.db.jooq.tables.pojos.PageTag.class, configuration);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    protected Record2<Long, Long> getId(de.vorb.sokrates.db.jooq.tables.pojos.PageTag object) {
        return compositeKeyRecord(object.getTagId(), object.getPageId());
    }

    /**
     * Fetch records that have <code>PAGE_ID IN (values)</code>
     */
    public List<de.vorb.sokrates.db.jooq.tables.pojos.PageTag> fetchByPageId(Long... values) {
        return fetch(PageTag.PAGE_TAG.PAGE_ID, values);
    }

    /**
     * Fetch records that have <code>TAG_ID IN (values)</code>
     */
    public List<de.vorb.sokrates.db.jooq.tables.pojos.PageTag> fetchByTagId(Long... values) {
        return fetch(PageTag.PAGE_TAG.TAG_ID, values);
    }
}
