spring.datasource:
  url: jdbc:h2:./sokrates
  driver-class-name: org.h2.Driver
  username: sa
  password:

sokrates:
  site:
    default-locale: en-US
  directory:
    output: out/
    templates: src/site/resources/templates/
  generator:
    pandoc-executable: E:\Program Files\Pandoc\pandoc.exe
    extension-mapping:
      md: html
    generate-rules:
      - pattern: src/site/markdown/**/*.md
        base-directory: src/site/markdown
        format: markdown
    copy-rules:
      - pattern: src/site/markdown/**/*
        base-directory: src/site/markdown
  indexes:
    - name: Blog index
      template: index.html
      output-file: index.html
      order-by:
        - created_at DESC
    - name: Feed
      template: feed.xml
      output-file: feed.xml
      order-by:
        - created_at DESC
      limit: 10
