/*
 * This file is generated by jOOQ.
*/
package de.vorb.sokrates.db.jooq;


import javax.annotation.Generated;

import org.jooq.Sequence;
import org.jooq.impl.SequenceImpl;


/**
 * Convenience access to all sequences in PUBLIC
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.9.2"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Sequences {

    /**
     * The sequence <code>PUBLIC.SYSTEM_SEQUENCE_016C3E6B_7D1F_4D8B_9280_DE0CA950385E</code>
     */
    public static final Sequence<Long> SYSTEM_SEQUENCE_016C3E6B_7D1F_4D8B_9280_DE0CA950385E = new SequenceImpl<Long>("SYSTEM_SEQUENCE_016C3E6B_7D1F_4D8B_9280_DE0CA950385E", Public.PUBLIC, org.jooq.impl.SQLDataType.BIGINT);

    /**
     * The sequence <code>PUBLIC.SYSTEM_SEQUENCE_78812057_3AC2_4B4A_A874_6AC5C405C630</code>
     */
    public static final Sequence<Long> SYSTEM_SEQUENCE_78812057_3AC2_4B4A_A874_6AC5C405C630 = new SequenceImpl<Long>("SYSTEM_SEQUENCE_78812057_3AC2_4B4A_A874_6AC5C405C630", Public.PUBLIC, org.jooq.impl.SQLDataType.BIGINT);
}
