/*
 * This file is generated by jOOQ.
*/
package de.vorb.sokrates.db.jooq.tables.records;


import de.vorb.sokrates.db.jooq.tables.PageTag;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.Record2;
import org.jooq.Row2;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.10.2"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class PageTagRecord extends UpdatableRecordImpl<PageTagRecord> implements Record2<Long, Long> {

    private static final long serialVersionUID = 1575103630;

    /**
     * Setter for <code>PUBLIC.PAGE_TAG.PAGE_ID</code>.
     */
    public PageTagRecord setPageId(Long value) {
        set(0, value);
        return this;
    }

    /**
     * Getter for <code>PUBLIC.PAGE_TAG.PAGE_ID</code>.
     */
    public Long getPageId() {
        return (Long) get(0);
    }

    /**
     * Setter for <code>PUBLIC.PAGE_TAG.TAG_ID</code>.
     */
    public PageTagRecord setTagId(Long value) {
        set(1, value);
        return this;
    }

    /**
     * Getter for <code>PUBLIC.PAGE_TAG.TAG_ID</code>.
     */
    public Long getTagId() {
        return (Long) get(1);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Record2<Long, Long> key() {
        return (Record2) super.key();
    }

    // -------------------------------------------------------------------------
    // Record2 type implementation
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Row2<Long, Long> fieldsRow() {
        return (Row2) super.fieldsRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Row2<Long, Long> valuesRow() {
        return (Row2) super.valuesRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Long> field1() {
        return PageTag.PAGE_TAG.PAGE_ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Long> field2() {
        return PageTag.PAGE_TAG.TAG_ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Long component1() {
        return getPageId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Long component2() {
        return getTagId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Long value1() {
        return getPageId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Long value2() {
        return getTagId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public PageTagRecord value1(Long value) {
        setPageId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public PageTagRecord value2(Long value) {
        setTagId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public PageTagRecord values(Long value1, Long value2) {
        value1(value1);
        value2(value2);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached PageTagRecord
     */
    public PageTagRecord() {
        super(PageTag.PAGE_TAG);
    }

    /**
     * Create a detached, initialised PageTagRecord
     */
    public PageTagRecord(Long pageId, Long tagId) {
        super(PageTag.PAGE_TAG);

        set(0, pageId);
        set(1, tagId);
    }
}
