/*
 * This file is generated by jOOQ.
*/
package de.vorb.sokrates.db.jooq.tables.records;


import de.vorb.sokrates.db.jooq.tables.Page;

import java.net.URI;
import java.nio.file.Path;
import java.time.LocalDate;
import java.util.Locale;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record9;
import org.jooq.Row9;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.10.2"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class PageRecord extends UpdatableRecordImpl<PageRecord> implements Record9<Long, Path, String, URI, String, LocalDate, LocalDate, Locale, byte[]> {

    private static final long serialVersionUID = -21426367;

    /**
     * Setter for <code>PUBLIC.PAGE.ID</code>.
     */
    public PageRecord setId(Long value) {
        set(0, value);
        return this;
    }

    /**
     * Getter for <code>PUBLIC.PAGE.ID</code>.
     */
    public Long getId() {
        return (Long) get(0);
    }

    /**
     * Setter for <code>PUBLIC.PAGE.SOURCE_FILE_PATH</code>.
     */
    public PageRecord setSourceFilePath(Path value) {
        set(1, value);
        return this;
    }

    /**
     * Getter for <code>PUBLIC.PAGE.SOURCE_FILE_PATH</code>.
     */
    public Path getSourceFilePath() {
        return (Path) get(1);
    }

    /**
     * Setter for <code>PUBLIC.PAGE.SOURCE_FILE_FORMAT</code>.
     */
    public PageRecord setSourceFileFormat(String value) {
        set(2, value);
        return this;
    }

    /**
     * Getter for <code>PUBLIC.PAGE.SOURCE_FILE_FORMAT</code>.
     */
    public String getSourceFileFormat() {
        return (String) get(2);
    }

    /**
     * Setter for <code>PUBLIC.PAGE.URL</code>.
     */
    public PageRecord setUrl(URI value) {
        set(3, value);
        return this;
    }

    /**
     * Getter for <code>PUBLIC.PAGE.URL</code>.
     */
    public URI getUrl() {
        return (URI) get(3);
    }

    /**
     * Setter for <code>PUBLIC.PAGE.TITLE</code>.
     */
    public PageRecord setTitle(String value) {
        set(4, value);
        return this;
    }

    /**
     * Getter for <code>PUBLIC.PAGE.TITLE</code>.
     */
    public String getTitle() {
        return (String) get(4);
    }

    /**
     * Setter for <code>PUBLIC.PAGE.CREATED_AT</code>.
     */
    public PageRecord setCreatedAt(LocalDate value) {
        set(5, value);
        return this;
    }

    /**
     * Getter for <code>PUBLIC.PAGE.CREATED_AT</code>.
     */
    public LocalDate getCreatedAt() {
        return (LocalDate) get(5);
    }

    /**
     * Setter for <code>PUBLIC.PAGE.LAST_MODIFIED_AT</code>.
     */
    public PageRecord setLastModifiedAt(LocalDate value) {
        set(6, value);
        return this;
    }

    /**
     * Getter for <code>PUBLIC.PAGE.LAST_MODIFIED_AT</code>.
     */
    public LocalDate getLastModifiedAt() {
        return (LocalDate) get(6);
    }

    /**
     * Setter for <code>PUBLIC.PAGE.LOCALE</code>.
     */
    public PageRecord setLocale(Locale value) {
        set(7, value);
        return this;
    }

    /**
     * Getter for <code>PUBLIC.PAGE.LOCALE</code>.
     */
    public Locale getLocale() {
        return (Locale) get(7);
    }

    /**
     * Setter for <code>PUBLIC.PAGE.CHECKSUM</code>.
     */
    public PageRecord setChecksum(byte... value) {
        set(8, value);
        return this;
    }

    /**
     * Getter for <code>PUBLIC.PAGE.CHECKSUM</code>.
     */
    public byte[] getChecksum() {
        return (byte[]) get(8);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Record1<Long> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record9 type implementation
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Row9<Long, Path, String, URI, String, LocalDate, LocalDate, Locale, byte[]> fieldsRow() {
        return (Row9) super.fieldsRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Row9<Long, Path, String, URI, String, LocalDate, LocalDate, Locale, byte[]> valuesRow() {
        return (Row9) super.valuesRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Long> field1() {
        return Page.PAGE.ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Path> field2() {
        return Page.PAGE.SOURCE_FILE_PATH;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field3() {
        return Page.PAGE.SOURCE_FILE_FORMAT;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<URI> field4() {
        return Page.PAGE.URL;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field5() {
        return Page.PAGE.TITLE;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<LocalDate> field6() {
        return Page.PAGE.CREATED_AT;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<LocalDate> field7() {
        return Page.PAGE.LAST_MODIFIED_AT;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Locale> field8() {
        return Page.PAGE.LOCALE;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<byte[]> field9() {
        return Page.PAGE.CHECKSUM;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Long component1() {
        return getId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Path component2() {
        return getSourceFilePath();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component3() {
        return getSourceFileFormat();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public URI component4() {
        return getUrl();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component5() {
        return getTitle();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public LocalDate component6() {
        return getCreatedAt();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public LocalDate component7() {
        return getLastModifiedAt();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Locale component8() {
        return getLocale();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public byte[] component9() {
        return getChecksum();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Long value1() {
        return getId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Path value2() {
        return getSourceFilePath();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value3() {
        return getSourceFileFormat();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public URI value4() {
        return getUrl();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value5() {
        return getTitle();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public LocalDate value6() {
        return getCreatedAt();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public LocalDate value7() {
        return getLastModifiedAt();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Locale value8() {
        return getLocale();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public byte[] value9() {
        return getChecksum();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public PageRecord value1(Long value) {
        setId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public PageRecord value2(Path value) {
        setSourceFilePath(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public PageRecord value3(String value) {
        setSourceFileFormat(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public PageRecord value4(URI value) {
        setUrl(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public PageRecord value5(String value) {
        setTitle(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public PageRecord value6(LocalDate value) {
        setCreatedAt(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public PageRecord value7(LocalDate value) {
        setLastModifiedAt(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public PageRecord value8(Locale value) {
        setLocale(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public PageRecord value9(byte... value) {
        setChecksum(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public PageRecord values(Long value1, Path value2, String value3, URI value4, String value5, LocalDate value6, LocalDate value7, Locale value8, byte[] value9) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        value5(value5);
        value6(value6);
        value7(value7);
        value8(value8);
        value9(value9);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached PageRecord
     */
    public PageRecord() {
        super(Page.PAGE);
    }

    /**
     * Create a detached, initialised PageRecord
     */
    public PageRecord(Long id, Path sourceFilePath, String sourceFileFormat, URI url, String title, LocalDate createdAt, LocalDate lastModifiedAt, Locale locale, byte[] checksum) {
        super(Page.PAGE);

        set(0, id);
        set(1, sourceFilePath);
        set(2, sourceFileFormat);
        set(3, url);
        set(4, title);
        set(5, createdAt);
        set(6, lastModifiedAt);
        set(7, locale);
        set(8, checksum);
    }
}
